services:
  deso:
    #    image: docker.io/desoprotocol/backend-dev:451a0a65e27da4ad68cb0705c63b1c964a1ce011
    build:
      context: ..
      dockerfile: backend/Dockerfile
    environment:
      - ADD_IPS=localhost:19000
      - PRIVATE_MODE=true
      - RUN_HOT_FEED_ROUTINE=false
      - API_PORT=18001
      - PROTOCOL_PORT=18000
      - TXINDEX=true
      - DATA_DIR=/pd/n0_00001
      - ACCESS_CONTROL_ALLOW_ORIGINS=*
      - SECURE_HEADER_ALLOW_HOSTS=localhost:4200
      - SECURE_HEADER_DEVELOPMENT=true
      - BLOCK_CYPHER_API_KEY=092dae962ea44b02809a4c74408b42a1
      - MIN_SATOSHIS_FOR_PROFILE=0
      - EXPOSE_GLOBAL_STATE=false
      - SHOW_PROCESSING_SPINNERS=true
      - COMP_PROFILE_CREATION=false

      # Blocks syncing settings:
      - SYNC_TYPE=blocksync
      - HYPERSYNC=false

      # Testnet Settings:
      - REGTEST=false
      - TESTNET=true
      - CONNECT_IPS=35.192.117.201:18000
      - STATE_CHANGE_DIR=/ss/state-changes
      - TRUSTED_BLOCK_PRODUCER_PUBLIC_KEYS=
      - TRUSTED_BLOCK_PRODUCER_START_HEIGHT=10000000
    ports:
      - '18000:18000'
      - '18001:18001'
      - '19000:19000'
    volumes:
      - pd_volume:/pd
      - ss_volume:/ss
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://deso:18001/api/v0/health-check || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 10s
    command: ["run"]

  pdh:
    #    image: docker.io/desoprotocol/postgres-data-handler:c2ff0e2921911d2581685e1794a1324724997c64
    build:
      context: ..
      dockerfile: web-data-handler/Dockerfile
    environment:
      # Removed DB_* environment variables because no Postgres is used.
      - STATE_CHANGE_DIR=/ss/state-changes
      - CONSUMER_PROGRESS_DIR=/ss/consumer-progress
      - BATCH_BYTES=500000
      - THREAD_LIMIT=10
      - CALCULATE_EXPLORER_STATISTICS=false
      - LOG_QUERIES=false
      - IS_TESTNET=true
    command: ["run"]
    volumes:
      - ss_volume:/ss

volumes:
  pd_volume:
  ss_volume:
